test: test-hamming-distance test-post-order-traversal test-string-compression

test-hamming-distance:
	python -m unittest -v hamming_distance.py

test-post-order-traversal:
	python -m unittest -v post_order_traversal.py

test-string-compression:
	python -m unittest -v string_compression

